#!/bin/bash

EXTRA_CMAKE_ARGS=""
if [[ `uname` == 'Darwin' ]];
then
    export CMAKE_OSX_DEPLOYMENT_TARGET=""
    EXTRA_CMAKE_ARGS="-DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET} -DZMQ_BUILD_FRAMEWORK=OFF"
else
    export LIBRARY_SEARCH_VAR=LD_LIBRARY_PATH
fi
export EXTRA_CMAKE_ARGS

mkdir build
cd build
cmake -D WITH_PERF_TOOL=OFF -D ZMQ_BUILD_TESTS=ON -D ENABLE_CPACK=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=$PREFIX -D CMAKE_INSTALL_LIBDIR=$PREFIX/lib ${EXTRA_CMAKE_ARGS} ..
make install

