{% set name = "zeromq" %}
{% set version = "4.2.1" %}
{% set sha256 = "27d1e82a099228ee85a7ddb2260f40830212402c605a4a10b5e5498a7e0e9d03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeromq/libzmq/releases/download/v{{ version }}/zeromq-{{ version }}.tar.gz

  sha256: {{ sha256 }}
  patches:
    # Fixes in libzmq's cmake which enable a cmake build on windows, and cmake
    # install in general.
    #
    # zeromq/libzmq#2304
    # zeromq/libzmq#2295
    # zeromq/libzmq#2294
    # zeromq/libzmq#2311
    # zeromq/libzmq#2317
    # zeromq/libzmq#2318
    #
    - 0001-Windows-cmake-build-fixed.patch
    - 0002-CPack-option-and-.txt-files-installation-dir.patch
    - 0003-cmake-install-config-file.patch
    - 0004-INSTALLATION-instructions.patch
    - 0005-cmake-install-on-linux-fixed.patch
    - 0006-Problem-name-of-static-library-generated-by-cmake-di.patch
    - 0007-Problem-cmake-artefacts-different-from-make-generate.patch
    - 0008-CMake-static-library-output-does-not-match-ZeroMQ-Co.patch

build:
  number: 1
  skip: true  # [win and py27]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake
    - libsodium
    - python  # [win]
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]

  run:
    - libsodium
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]

test:
  commands:
    - test -f ${PREFIX}/lib/libzmq.a         # [unix]
    - test -f ${PREFIX}/lib/libzmq.so        # [linux]
    - test -f ${PREFIX}/lib/libzmq.so.5      # [linux]
    - test -f ${PREFIX}/lib/libzmq.dylib     # [osx]
    - test -f ${PREFIX}/lib/libzmq.dylib.5   # [osx]
    - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfig.cmake         # [unix]
    - test -f ${PREFIX}/share/cmake/ZeroMQ/ZeroMQConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_LIB%\libzmq-mt-s-{{ version | replace('.', '_') }}.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_BIN%\libzmq-mt-{{ version | replace('.', '_') }}.dll (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_LIB%\libzmq-mt-{{ version | replace('.', '_') }}.lib (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_BIN%\libzmq.dll (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_LIB%\libzmq.lib (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\ZeroMQ\ZeroMQConfig.cmake (exit 0) else (exit 1)           # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\ZeroMQ\ZeroMQConfigVersion.cmake (exit 0) else (exit 1)    # [win]

about:
  home: http://zeromq.org
  license: LGPL 3
  summary: A high-performance asynchronous messaging library.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - SylvainCorlay
    - JohanMabille
